### PR TITLE
Updates German translation

### PR DESCRIPTION
**Pull request by cpfaff**
* Improves the patterns
	- moves from "zeitcode|offset" to "springe" (Jump) which feels
	  more native as voice command

* Improves the strings
	- Translates the examples
	- Improves other strings

### CODE REVIEW

**Comment by cpfaff** [comment]
I noticed two things. 

1. The blue button does not use the translation! The text seems hardcoded to "Usage Examples"
2. There is an example 

```
Watch episode once more With Feeling of Buffy the vampire slayer
```

But I do not see how the recognition patterns would support this command.

**Comment by cpfaff** [comment]
And I have a question. What does "Resume if in progress" actually do?

**Comment by cpfaff** [comment]
Could you provide me with an updated version of the app if you merged the changes. That would be amazing. So I can test it.

**Comment by atomjack** [comment]
Alrighty, here ya go: https://www.dropbox.com/s/u68168tu5ndl7t5/VoiceControlForPlex2.0.3b1.apk?dl=0

I left the version exactly the same, so just redownload that and install over it.

I'm going out of town later today until Sunday so I won't be able to do more until then.

**Comment by cpfaff** [comment]
Thanks!

**Pull request merged**
