### PR TITLE
Adds German strings and patterns

### PR DESCRIPTION
**Pull request by cpfaff**
This is a first version of a German translation. Might still need some refinement but I would try it first and then make the changes if needed. How can I use the German translation in the application when installed from the play store then. Is it used automatically when the system language defaults to the language?

### CODE REVIEW

**Comment by atomjack** [comment]
Thank you so much!!! Yes, it will be used automatically if the system language is defaulted to a language for which the app has a translation. I tested it out using Google Translate and having that speak out "schau aliens" and "spiele aliens" and it worked.

Here's an apk for you to try it out with: https://www.dropbox.com/s/u68168tu5ndl7t5/VoiceControlForPlex2.0.3b1.apk?dl=0

Once you are done with any refinements I will push out 2.0.3, just do another pull request. You are probably already planning this but make sure to translate the help_usage string, as it's currently showing the english way of saying things. 

How would you like to be credited?

Thanks again!

**Comment by cpfaff** [comment]
On So, Mai 17, 2015 at 12:12:09 -0700, Chris Bellew wrote:
> Thank you so much!!! Yes, it will be used automatically if the system
> language is defaulted to a language for which the app has a
> translation. I tested it out using Google Translate and having that
> speak out "schau aliens" and "spiele aliens" and it worked.
> 

You are welcome. Thanks for the app. I will give it a try this evening
and over the next few days to see if the files need to be tweaked.
Yesterday I tried it with the English version but it did not work at all
and I do not know why. Hopefully this is just related somehow to
differences in language of the app and the system and no other problem.
I was saying "play next episode of ..." it showed me "search next
episode ..." so seems that it actually understood me right then it took
a while before an error message popped up as toast that said "sorry
nothing found". This was done using the home-shortcut, the app is signed
in to myPlex and I did the manual connect to the client in the app via
the cast symbol. By the way. Is this manual connection necessary in
order to make the voice recognition work. Or does the home shortcut and
the tasker/autovoice combination do this automatically.

> Here's an apk for you to try it out with: https://www.dropbox.com/s/u68168tu5ndl7t5/VoiceControlForPlex2.0.3b1.apk?dl=0
> 
> Once you are done with any refinements I will push out 2.0.3, just do another pull request. You are probably already planning this but make sure to translate the help_usage string, as it's currently showing the english way of saying things. 
> 
> How would you like to be credited?

You could mention me e.g. under translations on a credit page if you
have one.
> 
> Thanks again!
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/atomjack/VoiceControlForPlex/pull/8#issuecomment-102836210

-- 
Claas-Thido Pfaff

**Comment by cpfaff** [comment]
Are the patterns interpreted case sensitive?

**Comment by atomjack** [comment]
The manual connection is not required - but unless you specify a client to play to, you have to connect to a client at least once. You'll notice it will then say that that client is your default client. If you aren't connected to any client when you trigger voice recognition, it will just use the default client (unless you're using a shortcut that has a different client specified).

The patterns are interpreted in all lowercase - when I get the spoken string from Google's voice recognition, I'm converting it to all lowercase before comparing it to the patterns, so as long as they (the pattern strings) are all in lowercase it should match properly.

What I meant by how do you want to be credited is, as 'cpfaff'? Or your full name? The credit will go in the changelog, as well as the change notes in the Play Store when I submit this new version (once you're done with your translations of course:).

When you had problems searching for something, keep in mind that if you do "play the next episode of..." and you specify a show that does not have any episodes on deck, it will say nothing found. So you may also wanna test it on a movie, and/or a specified season/episode of a show.

**Comment by atomjack** [comment]
Also, I just made an update to the patterns (your German translation included) to allow for 'playback' to be optional when pausing, playing, or stopping. So now you can say:pause, pause playback, resume, resume playback, stop, stop playback.

I also noticed that in German, the words in those phrases are reversed, so "pause playback" translates to "wiedergabe pausieren" (instead of "pausieren wiedergabe"). The fact of this necessitated me to make a small change to the pattern_recognition pattern (the first one in the file) to reflect this. That was my bad, and I've added a comment above the three patterns (pause,resume,stop) indicating this. 

This pattern_recognition pattern is used in a few places to know whether or not to proceed with parsing the input that was spoken - it then uses the separate patterns to figure out which action to take.

**Comment by cpfaff** [comment]
>The manual connection is not required - but unless you specify a client to play to, you have to connect to a client at least once. You'll notice it will then say that that client is your default client. If you aren't connected to any client when you trigger voice recognition, it will just use the default client (unless you're using a shortcut that has a different client specified).

Ok thanks 

> The patterns are interpreted in all lowercase - when I get the spoken string from Google's voice recognition, I'm converting it to all lowercase before comparing it to the patterns, so as long as they (the pattern strings) are all in lowercase it should match properly.

That makes sense and eliminates a bad source of error.

>What I meant by how do you want to be credited is, as 'cpfaff'? Or your full name? The credit will go in the changelog, as well as the change notes in the Play Store when I submit this new version (once you're done with your translations of course:).

You can mention me using the full name. You find it in my GitHub Profile

> When you had problems searching for something, keep in mind that if you do "play the next episode of..." and you specify a show that does not have any episodes on deck, it will say nothing found. So you may also wanna test it on a movie, and/or a specified season/episode of a show.

Actually I was looking for something that was on-deck. But it did not work anyway. Maybe this is also related to other things as I have installed the latest nightly of Cyanogenmod which might break some
things. Tasker profiles with AutoVoice are also not triggered properly currently and I do not know why.

**Comment by cpfaff** [comment]
>Also, I just made an update to the patterns (your German translation included) to allow for 'playback' to be optional when pausing, playing, or stopping. So now you can say:pause, pause playback, resume, resume playback, stop, stop playback.

>I also noticed that in German, the words in those phrases are reversed, so "pause playback" translates to "wiedergabe pausieren" (instead of "pausieren wiedergabe"). The fact of this necessitated me to make a small change to the pattern_recognition pattern (the first one in the file) to reflect this. That was my bad, and I've added a comment above the three patterns (pause,resume,stop) indicating this.

>This pattern_recognition pattern is used in a few places to know whether or not to proceed with parsing the input that was spoken - it then uses the separate patterns to figure out which action to take.

Cool. Maybe this was the reason that the playback control did not work for me either. Yes right it is the other way around in German. I am looking forward to test the updated version

**Pull request merged**
